# Generated by Django 5.1.7 on 2025-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_book_user_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Ficção'), ('non_fiction', 'Não-ficção'), ('adventure', 'Aventura'), ('romance', 'Romance'), ('mystery', 'Mistério'), ('science_fiction', 'Ficção científica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='classification',
            field=models.CharField(choices=[('all_ages', 'Todas as idades'), ('10_and_up', '10 anos ou mais'), ('13_and_up', '13 anos ou mais'), ('16_and_up', '16 anos ou mais'), ('18_and_up', '18 anos ou mais')], max_length=20),
        ),
    ]
