# Generated by Django 5.1.7 on 2025-04-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_bookrequest_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fantasy', 'Fantasia'), ('non_fiction', 'Não-ficção'), ('adventure', 'Aventura'), ('romance', 'Romance'), ('horror', 'Horror'), ('science_fiction', 'Ficção científica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
