# Generated by Django 5.1.7 on 2025-04-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_book_category_alter_book_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('awaiting_pickup', 'Aguardando Retirada'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
