# Generated by Django 5.1.7 on 2025-04-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_pickuppoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_point_books', to='common.pickuppoint'),
        ),
    ]
