# Generated by Django 5.1.7 on 2025-04-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_book_pickup_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pickup_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.pickuppoint'),
            preserve_default=False,
        ),
    ]
