# Generated by Django 5.1.7 on 2025-04-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_book_pickup_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pickup_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.pickuppoint'),
        ),
    ]
