# Generated by Django 5.1.7 on 2025-04-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_book_pickup_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='delivery_option',
        ),
    ]
